services:
  db:
    image: postgres:16.4
    # ... other db configurations
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
    networks:
      - my_network

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - DB_USER=${DB_USER} # Pass DB_USER to the web container
      - DB_NAME=${DB_NAME} # Pass DB_NAME to the web container
      - DB_MIGRATING=${DB_MIGRATING} # Pass DB_MIGRATING to the web container
    depends_on:
      - db
    networks:
      - my_network
    #command: ["./db-seed.sh"] # Run the seed script after the container starts

networks:
  my_network:
    name: my_network
    driver: bridge
